// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.28.0
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentStatus int32

const (
	AgentStatus_AVAILABLE AgentStatus = 0
	AgentStatus_BUSY      AgentStatus = 1
	AgentStatus_AWAY      AgentStatus = 2
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AVAILABLE",
		1: "BUSY",
		2: "AWAY",
	}
	AgentStatus_value = map[string]int32{
		"AVAILABLE": 0,
		"BUSY":      1,
		"AWAY":      2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Audio
	//	*AgentMessage_PullQueue
	//	*AgentMessage_Status
	Message       isAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterAgent {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetAudio() *AudioData {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *AgentMessage) GetPullQueue() *PullFromQueue {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_PullQueue); ok {
			return x.PullQueue
		}
	}
	return nil
}

func (x *AgentMessage) GetStatus() *AgentStatusUpdate {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_Register struct {
	Register *RegisterAgent `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Audio struct {
	Audio *AudioData `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type AgentMessage_PullQueue struct {
	PullQueue *PullFromQueue `protobuf:"bytes,3,opt,name=pull_queue,json=pullQueue,proto3,oneof"`
}

type AgentMessage_Status struct {
	Status *AgentStatusUpdate `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Message() {}

func (*AgentMessage_Audio) isAgentMessage_Message() {}

func (*AgentMessage_PullQueue) isAgentMessage_Message() {}

func (*AgentMessage_Status) isAgentMessage_Message() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_CallAssignment
	//	*ServerMessage_Audio
	//	*ServerMessage_CallEnded
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetCallAssignment() *CallAssignment {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_CallAssignment); ok {
			return x.CallAssignment
		}
	}
	return nil
}

func (x *ServerMessage) GetAudio() *AudioData {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ServerMessage) GetCallEnded() *CallEnded {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_CallEnded); ok {
			return x.CallEnded
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_CallAssignment struct {
	CallAssignment *CallAssignment `protobuf:"bytes,1,opt,name=call_assignment,json=callAssignment,proto3,oneof"`
}

type ServerMessage_Audio struct {
	Audio *AudioData `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type ServerMessage_CallEnded struct {
	CallEnded *CallEnded `protobuf:"bytes,3,opt,name=call_ended,json=callEnded,proto3,oneof"`
}

func (*ServerMessage_CallAssignment) isServerMessage_Message() {}

func (*ServerMessage_Audio) isServerMessage_Message() {}

func (*ServerMessage_CallEnded) isServerMessage_Message() {}

type RegisterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extension     string                 `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgent) Reset() {
	*x = RegisterAgent{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgent) ProtoMessage() {}

func (x *RegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgent.ProtoReflect.Descriptor instead.
func (*RegisterAgent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgent) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *RegisterAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AudioData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcmData       []byte                 `protobuf:"bytes,1,opt,name=pcm_data,json=pcmData,proto3" json:"pcm_data,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioData) Reset() {
	*x = AudioData{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioData) ProtoMessage() {}

func (x *AudioData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioData.ProtoReflect.Descriptor instead.
func (*AudioData) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AudioData) GetPcmData() []byte {
	if x != nil {
		return x.PcmData
	}
	return nil
}

func (x *AudioData) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type PullFromQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       int32                  `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullFromQueue) Reset() {
	*x = PullFromQueue{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullFromQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFromQueue) ProtoMessage() {}

func (x *PullFromQueue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFromQueue.ProtoReflect.Descriptor instead.
func (*PullFromQueue) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PullFromQueue) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type AgentStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AgentStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=agent.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusUpdate) Reset() {
	*x = AgentStatusUpdate{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusUpdate) ProtoMessage() {}

func (x *AgentStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusUpdate.ProtoReflect.Descriptor instead.
func (*AgentStatusUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentStatusUpdate) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AVAILABLE
}

type CallAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CallerId      string                 `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	QueueId       int32                  `protobuf:"varint,3,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAssignment) Reset() {
	*x = CallAssignment{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAssignment) ProtoMessage() {}

func (x *CallAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAssignment.ProtoReflect.Descriptor instead.
func (*CallAssignment) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *CallAssignment) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallAssignment) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *CallAssignment) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type CallEnded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEnded) Reset() {
	*x = CallEnded{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEnded) ProtoMessage() {}

func (x *CallEnded) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEnded.ProtoReflect.Descriptor instead.
func (*CallEnded) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CallEnded) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"\xe2\x01\n" +
	"\fAgentMessage\x122\n" +
	"\bregister\x18\x01 \x01(\v2\x14.agent.RegisterAgentH\x00R\bregister\x12(\n" +
	"\x05audio\x18\x02 \x01(\v2\x10.agent.AudioDataH\x00R\x05audio\x125\n" +
	"\n" +
	"pull_queue\x18\x03 \x01(\v2\x14.agent.PullFromQueueH\x00R\tpullQueue\x122\n" +
	"\x06status\x18\x04 \x01(\v2\x18.agent.AgentStatusUpdateH\x00R\x06statusB\t\n" +
	"\amessage\"\xb9\x01\n" +
	"\rServerMessage\x12@\n" +
	"\x0fcall_assignment\x18\x01 \x01(\v2\x15.agent.CallAssignmentH\x00R\x0ecallAssignment\x12(\n" +
	"\x05audio\x18\x02 \x01(\v2\x10.agent.AudioDataH\x00R\x05audio\x121\n" +
	"\n" +
	"call_ended\x18\x03 \x01(\v2\x10.agent.CallEndedH\x00R\tcallEndedB\t\n" +
	"\amessage\"A\n" +
	"\rRegisterAgent\x12\x1c\n" +
	"\textension\x18\x01 \x01(\tR\textension\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\tAudioData\x12\x19\n" +
	"\bpcm_data\x18\x01 \x01(\fR\apcmData\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"*\n" +
	"\rPullFromQueue\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\x05R\aqueueId\"?\n" +
	"\x11AgentStatusUpdate\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.agent.AgentStatusR\x06status\"a\n" +
	"\x0eCallAssignment\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\tR\bcallerId\x12\x19\n" +
	"\bqueue_id\x18\x03 \x01(\x05R\aqueueId\"$\n" +
	"\tCallEnded\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId*0\n" +
	"\vAgentStatus\x12\r\n" +
	"\tAVAILABLE\x10\x00\x12\b\n" +
	"\x04BUSY\x10\x01\x12\b\n" +
	"\x04AWAY\x10\x022H\n" +
	"\fAgentService\x128\n" +
	"\aConnect\x12\x13.agent.AgentMessage\x1a\x14.agent.ServerMessage(\x010\x01B:Z8github.com/Reverse-Call-Center/virtual-call-center/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_agent_proto_goTypes = []any{
	(AgentStatus)(0),          // 0: agent.AgentStatus
	(*AgentMessage)(nil),      // 1: agent.AgentMessage
	(*ServerMessage)(nil),     // 2: agent.ServerMessage
	(*RegisterAgent)(nil),     // 3: agent.RegisterAgent
	(*AudioData)(nil),         // 4: agent.AudioData
	(*PullFromQueue)(nil),     // 5: agent.PullFromQueue
	(*AgentStatusUpdate)(nil), // 6: agent.AgentStatusUpdate
	(*CallAssignment)(nil),    // 7: agent.CallAssignment
	(*CallEnded)(nil),         // 8: agent.CallEnded
}
var file_proto_agent_proto_depIdxs = []int32{
	3, // 0: agent.AgentMessage.register:type_name -> agent.RegisterAgent
	4, // 1: agent.AgentMessage.audio:type_name -> agent.AudioData
	5, // 2: agent.AgentMessage.pull_queue:type_name -> agent.PullFromQueue
	6, // 3: agent.AgentMessage.status:type_name -> agent.AgentStatusUpdate
	7, // 4: agent.ServerMessage.call_assignment:type_name -> agent.CallAssignment
	4, // 5: agent.ServerMessage.audio:type_name -> agent.AudioData
	8, // 6: agent.ServerMessage.call_ended:type_name -> agent.CallEnded
	0, // 7: agent.AgentStatusUpdate.status:type_name -> agent.AgentStatus
	1, // 8: agent.AgentService.Connect:input_type -> agent.AgentMessage
	2, // 9: agent.AgentService.Connect:output_type -> agent.ServerMessage
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Audio)(nil),
		(*AgentMessage_PullQueue)(nil),
		(*AgentMessage_Status)(nil),
	}
	file_proto_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_CallAssignment)(nil),
		(*ServerMessage_Audio)(nil),
		(*ServerMessage_CallEnded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
