// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/agent.proto

package proto

import (
	context "context"
	reflect "reflect"
	sync "sync"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentStatus int32

const (
	AgentStatus_AVAILABLE AgentStatus = 0
	AgentStatus_BUSY      AgentStatus = 1
	AgentStatus_AWAY      AgentStatus = 2
)

var (
	AgentStatus_name = map[int32]string{
		0: "AVAILABLE",
		1: "BUSY",
		2: "AWAY",
	}
	AgentStatus_value = map[string]int32{
		"AVAILABLE": 0,
		"BUSY":      1,
		"AWAY":      2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type AgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Audio
	//	*AgentMessage_PullQueue
	//	*AgentMessage_Status
	Message isAgentMessage_Message `protobuf_oneof:"message"`
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterAgent {
	if x, ok := x.GetMessage().(*AgentMessage_Register); ok {
		return x.Register
	}
	return nil
}

func (x *AgentMessage) GetAudio() *AudioData {
	if x, ok := x.GetMessage().(*AgentMessage_Audio); ok {
		return x.Audio
	}
	return nil
}

func (x *AgentMessage) GetPullQueue() *PullFromQueue {
	if x, ok := x.GetMessage().(*AgentMessage_PullQueue); ok {
		return x.PullQueue
	}
	return nil
}

func (x *AgentMessage) GetStatus() *AgentStatusUpdate {
	if x, ok := x.GetMessage().(*AgentMessage_Status); ok {
		return x.Status
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_Register struct {
	Register *RegisterAgent `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Audio struct {
	Audio *AudioData `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type AgentMessage_PullQueue struct {
	PullQueue *PullFromQueue `protobuf:"bytes,3,opt,name=pull_queue,json=pullQueue,proto3,oneof"`
}

type AgentMessage_Status struct {
	Status *AgentStatusUpdate `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Message() {}

func (*AgentMessage_Audio) isAgentMessage_Message() {}

func (*AgentMessage_PullQueue) isAgentMessage_Message() {}

func (*AgentMessage_Status) isAgentMessage_Message() {}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ServerMessage_CallAssignment
	//	*ServerMessage_Audio
	//	*ServerMessage_CallEnded
	Message isServerMessage_Message `protobuf_oneof:"message"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetCallAssignment() *CallAssignment {
	if x, ok := x.GetMessage().(*ServerMessage_CallAssignment); ok {
		return x.CallAssignment
	}
	return nil
}

func (x *ServerMessage) GetAudio() *AudioData {
	if x, ok := x.GetMessage().(*ServerMessage_Audio); ok {
		return x.Audio
	}
	return nil
}

func (x *ServerMessage) GetCallEnded() *CallEnded {
	if x, ok := x.GetMessage().(*ServerMessage_CallEnded); ok {
		return x.CallEnded
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_CallAssignment struct {
	CallAssignment *CallAssignment `protobuf:"bytes,1,opt,name=call_assignment,json=callAssignment,proto3,oneof"`
}

type ServerMessage_Audio struct {
	Audio *AudioData `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type ServerMessage_CallEnded struct {
	CallEnded *CallEnded `protobuf:"bytes,3,opt,name=call_ended,json=callEnded,proto3,oneof"`
}

func (*ServerMessage_CallAssignment) isServerMessage_Message() {}

func (*ServerMessage_Audio) isServerMessage_Message() {}

func (*ServerMessage_CallEnded) isServerMessage_Message() {}

type RegisterAgent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Extension string `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RegisterAgent) Reset() {
	*x = RegisterAgent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgent) ProtoMessage() {}

func (x *RegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterAgent) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *RegisterAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AudioData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PcmData []byte `protobuf:"bytes,1,opt,name=pcm_data,json=pcmData,proto3" json:"pcm_data,omitempty"`
	CallId  string `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
}

func (x *AudioData) Reset() {
	*x = AudioData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioData) ProtoMessage() {}

func (x *AudioData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AudioData) GetPcmData() []byte {
	if x != nil {
		return x.PcmData
	}
	return nil
}

func (x *AudioData) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type PullFromQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueueId int32 `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
}

func (x *PullFromQueue) Reset() {
	*x = PullFromQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullFromQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFromQueue) ProtoMessage() {}

func (x *PullFromQueue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PullFromQueue) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type AgentStatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status AgentStatus `protobuf:"varint,1,opt,name=status,proto3,enum=agent.AgentStatus" json:"status,omitempty"`
}

func (x *AgentStatusUpdate) Reset() {
	*x = AgentStatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusUpdate) ProtoMessage() {}

func (x *AgentStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentStatusUpdate) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AVAILABLE
}

type CallAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId   string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CallerId string `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	QueueId  int32  `protobuf:"varint,3,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
}

func (x *CallAssignment) Reset() {
	*x = CallAssignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAssignment) ProtoMessage() {}

func (x *CallAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallAssignment) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallAssignment) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *CallAssignment) GetQueueId() int32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type CallEnded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
}

func (x *CallEnded) Reset() {
	*x = CallEnded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEnded) ProtoMessage() {}

func (x *CallEnded) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallEnded) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

var file_proto_agent_proto_rawDesc = []byte{}

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData = file_proto_agent_proto_rawDesc
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_agent_proto_rawDescData)
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_agent_proto_goTypes = []interface{}{
	(AgentStatus)(0),          // 0: agent.AgentStatus
	(*AgentMessage)(nil),      // 1: agent.AgentMessage
	(*ServerMessage)(nil),     // 2: agent.ServerMessage
	(*RegisterAgent)(nil),     // 3: agent.RegisterAgent
	(*AudioData)(nil),         // 4: agent.AudioData
	(*PullFromQueue)(nil),     // 5: agent.PullFromQueue
	(*AgentStatusUpdate)(nil), // 6: agent.AgentStatusUpdate
	(*CallAssignment)(nil),    // 7: agent.CallAssignment
	(*CallEnded)(nil),         // 8: agent.CallEnded
}
var file_proto_agent_proto_depIdxs = []int32{
	3, // 0: agent.AgentMessage.register:type_name -> agent.RegisterAgent
	4, // 1: agent.AgentMessage.audio:type_name -> agent.AudioData
	5, // 2: agent.AgentMessage.pull_queue:type_name -> agent.PullFromQueue
	6, // 3: agent.AgentMessage.status:type_name -> agent.AgentStatusUpdate
	7, // 4: agent.ServerMessage.call_assignment:type_name -> agent.CallAssignment
	4, // 5: agent.ServerMessage.audio:type_name -> agent.AudioData
	8, // 6: agent.ServerMessage.call_ended:type_name -> agent.CallEnded
	0, // 7: agent.AgentStatusUpdate.status:type_name -> agent.AgentStatus
	1, // 8: agent.AgentService.Connect:input_type -> agent.AgentMessage
	2, // 9: agent.AgentService.Connect:output_type -> agent.ServerMessage
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterAgent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullFromQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentStatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallAssignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallEnded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_agent_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Audio)(nil),
		(*AgentMessage_PullQueue)(nil),
		(*AgentMessage_Status)(nil),
	}
	file_proto_agent_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ServerMessage_CallAssignment)(nil),
		(*ServerMessage_Audio)(nil),
		(*ServerMessage_CallEnded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_rawDesc = nil
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (AgentService_ConnectClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (AgentService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AgentService_serviceDesc.Streams[0], "/agent.AgentService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentService_ConnectClient{stream}
	return x, nil
}

type AgentService_ConnectClient interface {
	Send(*AgentMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type agentService_ConnectClient struct {
	grpc.ClientStream
}

func (x *agentService_ConnectClient) Send(m *AgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentService_ConnectClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	Connect(AgentService_ConnectServer) error
}

// UnimplementedAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (*UnimplementedAgentServiceServer) Connect(AgentService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Connect(&agentService_ConnectServer{stream})
}

type AgentService_ConnectServer interface {
	Send(*ServerMessage) error
	Recv() (*AgentMessage, error)
	grpc.ServerStream
}

type agentService_ConnectServer struct {
	grpc.ServerStream
}

func (x *agentService_ConnectServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentService_ConnectServer) Recv() (*AgentMessage, error) {
	m := new(AgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
